### ISSUE TITLE
off topic: help with porting SeaHash

### ISSUE THREAD

**Issue by JeffreySarnoff** [redox-os/tfs#34]
This is the only way I found to send this message.  I am porting SeaHash to Julia, and have run into a snag.  I get the correct values for inputs that are multiples of eight bytes, and incorrect results with intermediate lengths.  If appropriate, I can be reached via email and continue this there.  Thank you for nice function.

**Comment by ticki** [comment]
Hmm. Could you post the code?

**Comment by JeffreySarnoff** [comment]
Thank you. In preparing the code for posting, the problem fell away.  It works now.
