### ISSUE TITLE
Make all error after install. 

### ISSUE THREAD

**Issue by arthurvanzyl** [redox-os/tfs#45]
mkdir -p build/kernel
RUSTC="./krustc.sh" RUSTDOC="./krustdoc.sh" CARGO_INCREMENTAL=1 cargo rustc --manifest-path rust/src/libcollections/Cargo.toml --target x86_64-unknown-none --release -- -C soft-float -o build/kernel/libcollections.rlib
/bin/sh: 1: cargo: not found
mk/kernel.mk:2: recipe for target 'build/kernel/libcollections.rlib' failed
make: *** [build/kernel/libcollections.rlib] Error 127

Any suggestions please?

**Comment by bjorn3** [comment]
Does running `cargo` result in an error?

**Comment by arthurvanzyl** [comment]
excuse my ignorance.

/redox/Cargo.toml` is a virtual manifest, but this command requires running against an actual package in this workspace

**Comment by StefanoD** [comment]
I'm not sure what this has to do with TFS.

**Comment by ticki** [comment]
Wrong repo.
