### ISSUE TITLE
fix/publish atomic hashmap

### ISSUE THREAD

**Issue by m4b** [redox-os/tfs#47]
I would very much like to try out the atomic hashmap in another project, but as you mention, it isn't quite ready to be published.

Is there an ETA for this?

I tried fixing it myself to do some benchmarks, but it seems the build errors are actually nontrivial / the crate is more of a sketch than working code at this point, no?

**Comment by ticki** [comment]
> I tried fixing it myself to do some benchmarks, but it seems the build errors are actually nontrivial / the crate is more of a sketch than working code at this point, no?

It relies on `conc`, which itself isn't entirely complete (well, it's near to being, but still not there). When it's done, this is the next goal yes.

**Comment by m4b** [comment]
Cool, let me know if you need any help, eager to see this published.

**Comment by ticki** [comment]
Understandable. I hope it's ready within one month. I'm a bit busy right now, but it should be do-able for me.
