### ISSUE TITLE
Treiber: double free due to usage of compare_and_swap_raw

### ISSUE THREAD

**Issue by steffengy** [redox-os/tfs#57]
## Reproduction
```rust
let stack = Treiber::new();
stack.push(1); 
stack.push(200); 
stack.pop.unwrap(); 
::gc();
```

## Analysis

`stack.push(1)` works as expected.
During `stack.push(200);` the following happens:

- `push(200)` calls `self.head.compare_and_swap(...)`.
- `compare_and_swap(...)` calls `compare_and_swap_raw`
   which [enques the old (`1`) element as `Garbage`](https://github.com/redox-os/tfs/blob/9b40d809054b8f0df90c125afc5974933e2f372f/conc/src/atomic.rs#L258)

`stack.pop.unwrap()` also uses `compare_and_swap`, which in this case
queues `(=200)` as Garbage.

Then at the end, if you're running a sensitive allocator
(such as a debug build on windows) it will crash due to a double free:
- [`Garbage`::destroy](https://github.com/redox-os/tfs/blob/9b40d809054b8f0df90c125afc5974933e2f372f/conc/src/garbage.rs#L64) frees the element for (=1), during the `::gc` call.
- [`Treiber::drop`](https://github.com/redox-os/tfs/blob/9b40d809054b8f0df90c125afc5974933e2f372f/conc/src/sync/treiber.rs#L32) frees the head (=1)
again  (and the other items recursively, which doesn't happen here, since it crashes before)
which leads to the crash.

Conclusion:  
**To me it seems, that Treiber needs a different `compare_and_swap_raw`, which doesn't
enqueue the old elements as garbage, since they are still referenced after the swap.**

**Comment by steffengy** [comment]
Also to confirm this double-free on linux you might want to add
```rust
#![feature(alloc_system)]
extern crate alloc_system;
```

which should result in something like
```
*** Error in `/mnt/d/projects/rust/tfs/conc/target/debug/deps/conc-1bff7e175c46abd4': 
double free or corruption (fasttop): 0x00007f9490000b50 ***
```
when running it.

@ticki 
Can you confirm that my analysis above is indeed correct, or
is there something else going on?

**Comment by ticki** [comment]
I think you're spot on. Sorry I haven't responded. I mean to fix this tonight.

**Comment by ticki** [comment]
Check https://github.com/redox-os/tfs/commit/a558832f98f5810eb4daf07683ecbf944aa241a2, it fixes some of these issues, but introduces new ones ( :( )

**Comment by steffengy** [comment]
Yeah that seems to work now, but `simple1` fails:
```thread 'sync::treiber::tests::simple1' panicked at 'assertion failed: stack.pop().is_none()', src\sync\treiber.rs:198```

**Comment by ticki** [comment]
Fixed now. Can you confirm that?

**Comment by steffengy** [comment]
Everything's running fine.

**Comment by ticki** [comment]
Cool!
