### ISSUE TITLE
Ticki is back

### ISSUE THREAD

**Issue by pharaone** [redox-os/tfs#75]
![ticky is back](https://user-images.githubusercontent.com/17162630/33185221-6b141788-d081-11e7-893a-35feb9b0b7b5.PNG)
Hope you restart to work with redox ;D

**Comment by rroohhh** [comment]
[fyi](https://www.reddit.com/r/rust/comments/7dgw1w/this_week_in_redox_32/dpzcr86/)

**Comment by pharaone** [comment]
=(
